In [1]:
import torch

In [4]:
x = torch.FloatTensor([[[1,2],
                       [2,4]],
                      [[5,6],
                       [7,8]],
                      [[9,10],
                       [11,12]]])

print(x.size())

torch.Size([3, 2, 2])


In [5]:
print(x[0])
print(x[0,:])
print(x[0,:,:])

tensor([[1., 2.],
        [2., 4.]])
tensor([[1., 2.],
        [2., 4.]])
tensor([[1., 2.],
        [2., 4.]])


In [7]:
print(x[-1])
print(x[-1,:])
print(x[-1,:,:])

tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])
